package OOP3;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class MyExceptions {
    public static void main(String[] args) {
//        try {
//            System.out.println(10/0);
//        }catch (ArithmeticException exception){
//            //code
//            System.out.println("Error Caught! " + exception.getMessage());
//        }
//        System.out.println("Ayberk");


//        try {
//            int divByZero = 5/0;
//        }catch (ArithmeticException e){
//            System.out.println("Arithmetic Exception Caught: " + e.getMessage());
//        }finally {
//            System.out.println("This is the finally block");
//        }

//        myException();

        LinkedList


    }

//    public static void myException(){
//        throw new ArithmeticException("MyException");
//    }
}
